Resolves #115
itsalaidbacklife/cuttle-front-vue pull request #116
Opened 2022-01-16 00:00 UTC by byarmis

Added test for reported issue.

It was pointed out to me after the tests were written, but these are from the point of view of the player who didn't play the 9

2022-01-24 13:26 UTC, itsalaidbacklife commented on tests/e2e/specs/in_game/oneOffs.spec.js
> +			 */
With the bug fixed, rewrite step 4) to reflect the intended behavior, not the bug

2022-01-24 13:26 UTC, itsalaidbacklife commented on tests/e2e/specs/in_game/oneOffs.spec.js
> +			cy.log('STEP 1- P0 plays nine, targeting the Queen in play')
;

2022-01-24 13:33 UTC, itsalaidbacklife commented on tests/e2e/specs/in_game/oneOffs.spec.js
> +			cy.log('STEP 2- P1 plays a six, removing face cards')
;

2022-01-24 13:34 UTC, itsalaidbacklife commented on tests/e2e/specs/in_game/oneOffs.spec.js
> +		})
;

2022-01-25 00:56 UTC, itsalaidbacklife requested changes
Nice work; requesting a few chores

2022-01-29 15:54 UTC, itsalaidbacklife requested changes
Looks good. Remove the .only() and we're good to merge

2022-01-29 15:54 UTC, itsalaidbacklife commented on tests/e2e/specs/in_game/oneOffs.spec.js
> +		it.only('Plays a nine as a ONE-OFF, make sure that the bounced card is playable even if there is countering', ()=>{
Remove .only()

2022-01-31 03:30 UTC, byarmis commented on tests/e2e/specs/in_game/oneOffs.spec.js
> +		it.only('Plays a nine as a ONE-OFF, make sure that the bounced card is playable even if there is countering', ()=>{
agh crap sorry, good catch

2022-01-31 11:02 UTC, merged